name: Run tests

on:
  pull_request:
    branches: [release, main]
  push:
    branches: [release, main]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.12']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install pylint black |
          pip install .[dev]
      - name: Test lint, types, and format
        run: make test
